INSERT INTO poll_questions VALUES (1, 'Сколько вам лет?', '1.0.0');
INSERT INTO poll_questions VALUES (2, 'Насколько сложная была загрузка нашего ПО?', '1.0.0');
INSERT INTO poll_questions VALUES (3, 'Насколько быстрый был процесс загрузки нашего ПО?', '1.0.0');
INSERT INTO poll_questions VALUES (4, 'Насколько удобным Вы считаете интерфейс нашего ПО?', '1.0.0');
INSERT INTO poll_questions VALUES (5, 'Насколько полезной Вы считаете документацию, приложенную к нашему ПО?', '1.0.0');
INSERT INTO poll_questions VALUES (6, 'Насколько полезной Вы считаете поддержку нашего ПО?', '1.0.0');
INSERT INTO poll_questions VALUES (7, 'Как часто «зависает» наше ПО?', '1.0.0');
INSERT INTO poll_questions VALUES (8, 'Насколько Вы в общем довольны возможностями нашего ПО?', '1.0.0');
INSERT INTO poll_questions VALUES (9, 'В случае, если наше ПО стало бы платным, сколько Вы готовы за него заплатить?', '1.0.0');
INSERT INTO poll_questions VALUES (10, 'Вы бы рекомендовали наше ПО другим людям?', '1.0.0');

INSERT INTO poll_answers VALUES (1, '<10', 1, 2, 1);
INSERT INTO poll_answers VALUES (2, '10-20', 1, 2, 2);
INSERT INTO poll_answers VALUES (3, '30-40', 1, 2, 3);
INSERT INTO poll_answers VALUES (4, '50-60', 1, 2, 4);
INSERT INTO poll_answers VALUES (5, '>70', 1, 2, 5);
INSERT INTO poll_answers VALUES (6, 'Очень простая', 2, 3, 1);
INSERT INTO poll_answers VALUES (7, 'Скорее простая', 2, 3, 2);
INSERT INTO poll_answers VALUES (8, 'Нормальная', 2, 3, 3);
INSERT INTO poll_answers VALUES (9, 'Скорее сложная', 2, 3, 4);
INSERT INTO poll_answers VALUES (10, 'Очень сложная', 2, 3, 5);
INSERT INTO poll_answers VALUES (11, 'Очень быстрый', 3, 4, 1);
INSERT INTO poll_answers VALUES (12, 'Скорее быстрый', 3, 4, 2);
INSERT INTO poll_answers VALUES (13, 'Нормальный', 3, 4, 3);
INSERT INTO poll_answers VALUES (14, 'Скорее медленный', 3, 4, 4);
INSERT INTO poll_answers VALUES (15, 'Очень медленный', 3, 4, 5);
INSERT INTO poll_answers VALUES (16, 'Очень удобным', 4, 5, 1);
INSERT INTO poll_answers VALUES (17, 'Скорее удобным', 4, 5, 2);
INSERT INTO poll_answers VALUES (18, 'Нормальным', 4, 5, 3);
INSERT INTO poll_answers VALUES (19, 'Скорее неудобным', 4, 5, 4);
INSERT INTO poll_answers VALUES (20, 'Совсем неудобным', 4, 5, 5);
INSERT INTO poll_answers VALUES (21, 'Очень полезной', 5, 6, 1);
INSERT INTO poll_answers VALUES (22, 'Скорее полезной', 5, 6, 2);
INSERT INTO poll_answers VALUES (23, 'Нормальной', 5, 6, 3);
INSERT INTO poll_answers VALUES (24, 'Скорее бесполезной', 5, 6, 4);
INSERT INTO poll_answers VALUES (25, 'Полностью бесполезой', 5, 6, 5);
INSERT INTO poll_answers VALUES (26, 'Очень полезной', 6, 7, 1);
INSERT INTO poll_answers VALUES (27, 'Скорее полезной', 6, 7, 2);
INSERT INTO poll_answers VALUES (28, 'Нормальной', 6, 7, 3);
INSERT INTO poll_answers VALUES (29, 'Скорее бесполезной', 6, 7, 4);
INSERT INTO poll_answers VALUES (30, 'Полностью бесполезой', 6, 7, 5);
INSERT INTO poll_answers VALUES (31, 'Никогда', 7, 8, 1);
INSERT INTO poll_answers VALUES (32, 'Почти никогда', 7, 8, 2);
INSERT INTO poll_answers VALUES (33, 'Время от времени', 7, 8, 3);
INSERT INTO poll_answers VALUES (34, 'Сравнительно часто', 7, 8, 4);
INSERT INTO poll_answers VALUES (35, 'Очень часто', 7, 8, 5);
INSERT INTO poll_answers VALUES (36, 'Я очень доволен/льна', 8, 9, 1);
INSERT INTO poll_answers VALUES (37, 'Я недоволен/льна', 8, 9, 2);
INSERT INTO poll_answers VALUES (38, 'Я скорее доволен/льна', 8, 9, 3);
INSERT INTO poll_answers VALUES (39, 'Я средне доволен/льна', 8, 9, 4);
INSERT INTO poll_answers VALUES (40, 'Я скорее недоволен/льна', 8, 9, 5);
INSERT INTO poll_answers VALUES (41, 'Я скорее недоволен/льна', 8, 9, 6);
INSERT INTO poll_answers VALUES (42, 'Я полностью недоволен/льна', 8, 9, 7);
INSERT INTO poll_answers VALUES (43, '0', 9, 10, 1);
INSERT INTO poll_answers VALUES (44, '0-10', 9, 10, 2);
INSERT INTO poll_answers VALUES (45, '10-50', 9, 10, 3);
INSERT INTO poll_answers VALUES (46, '50-100', 9, 10, 4);
INSERT INTO poll_answers VALUES (47, '100++', 9, 10, 5);
INSERT INTO poll_answers VALUES (48, 'Несомненно да', 10, null, 1);
INSERT INTO poll_answers VALUES (49, 'Вероятно да', 10, null, 2);
INSERT INTO poll_answers VALUES (50, 'Не знаю', 10, null, 3);
INSERT INTO poll_answers VALUES (51, 'Вероятно нет', 10, null, 4);
INSERT INTO poll_answers VALUES (52, 'Точно нет', 10, null, 5);